#!/bin/bash
set -euo pipefail
: "${AUTHENTIK_POSTGRES_PASSWORD:?set AUTHENTIK_POSTGRES_PASSWORD}"
: "${OPENBAO_POSTGRES_PASSWORD:?set OPENBAO_POSTGRES_PASSWORD}"
psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
CREATE USER authentik WITH PASSWORD '${AUTHENTIK_POSTGRES_PASSWORD}';
CREATE DATABASE authentik OWNER authentik;
CREATE USER openbao WITH PASSWORD '${OPENBAO_POSTGRES_PASSWORD}';
CREATE DATABASE openbao OWNER openbao;
EOSQL
