config:
  ## Hetzner Cloud Configuration
  hcloud-security-cluster:clusterName: gmh-cloud
  hcloud-security-cluster:locationName: ash
  hcloud-security-cluster:hcloudToken:
    secure: v1:DVBufza6q9TMap35:jdrhIcoDZU6qa1ZDm/G+ShVyhDXrLFUd1OmpklMAlRxLKDChKCtWlzirDbNI39bo36abInp/MDhQx1kAApff96weFMjOGqC0iwacY4vjkn0=
  ## Hardware Configuration
  hcloud-security-cluster:disableArm: "true"
  ## Kubernetes Configuration
  hcloud-security-cluster:kubernetesVersion: "1.35.1"
  hcloud-security-cluster:controlPlaneNodes: |
    [
      {"id":1,"type":"cpx21"}
    ]
  hcloud-security-cluster:workerNodes: |
    [
      {"id":1,"type":"cpx31"},
      {"id":2,"type":"cpx31"}
    ]
  ## Talos Configuration
  hcloud-security-cluster:talosImageIdX86: "361342154"
  hcloud-security-cluster:talosVersion: "v1.12.4"
  ## Network Configuration
  hcloud-security-cluster:enableFloatingIp: "true"
  hcloud-security-cluster:enableIpv6: "true"
  hcloud-security-cluster:networkIpv4Cidr: "10.99.0.0/16"
  hcloud-security-cluster:nodeIpv4Cidr: "10.99.1.0/24"
  hcloud-security-cluster:firewallUseCurrentIp: "true"
encryptionsalt: v1:kDy+AkadoSk=:v1:1wx8z4Pgp9ErLmIr:qoNdZYCRpYla4ADazUiOGnVmcQvuRA==
