encryptionsalt: v1:RYR+lBGwvMQ=:v1:VQpNtuaWisZ5XZvB:Vl2AvEftrHThaLqDjwjvN/bjKVHLSA==
config:
  hcloud-security-cluster:hcloudToken:
    secure: v1:+Ha+ojjBBCaEyJc8:esQGZv4IDlKGKAxZez44I7kMEQoU5evaLYfVlPodGyccByED0ClHFJWnDu5EMr0UUFMsqxvr1SRUjtj4I29MGHr36kZQ+L2aZL5xfLH0TPg=
