encryptionsalt: v1:ehZfVlNdXnU=:v1:AOvW8icqeSLt51Da:ELre+WYuMI68bUN2riG0IqlwZJkGkQ==
config:
  hcloud:token:
    secure: v1:3hRAPEztws1gJQRX:mZdqqKFPq1ho7a5D5vpsWFigY7Pdl2KkhOmybgM1SVtEddUODbNw0OHpIyUub4mesQ+yE84urzYR+DT/tLp+gb4SluamiaQ89rflu/Yl/68=
